eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: wufeng
    password: wufeng
    listener:
      concurrency: 2
      max-concurrency: 2

